package com.airmap.airmapsdk.models

import com.squareup.moshi.JsonClass

/**
 * Even though this is a data class, this requires a custom equals and hashcode implementation because of the ByteArray
 */
@JsonClass(generateAdapter = true)
data class Comm(val key: ByteArray) {

    /**
     * Generated by Android Studio suggestion
     */
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Comm

        if (!key.contentEquals(other.key)) return false

        return true
    }

    /**
     * Generated by Android Studio suggestion
     */
    override fun hashCode(): Int {
        return key.contentHashCode()
    }
}
