package com.airmap.airmapsdk.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Even though this is a data class, this requires a custom equals and hashcode implementation because of the ByteArray
 */
@JsonClass(generateAdapter = true)
data class Comm(
    @Json(name = "key") val key: ByteArray
) {

    /**
     * Generated by Android Studio suggestion
     */
    override fun equals(other: Any?) = when {
        this === other -> true
        javaClass != other?.javaClass -> false
        else -> key.contentEquals((other as Comm).key)
    }

    /**
     * Generated by Android Studio suggestion
     */
    override fun hashCode() = key.contentHashCode()
}
